import json
import os
import requests
import logging
import time
import base64
from helper_functions.github_api_request_func import github_api_request

# Configure logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def raise_PR(code_fix , file_path):
    try:
        # Extract environment variables
        github_token = os.environ['GITHUB_TOKEN']
        repo_owner = os.environ['GITHUB_REPO_OWNER']
        repo_name = os.environ['GITHUB_REPO_NAME']
        github_dev_branch = 'feature/backend'
        github_test_branch = 'feature/test'
        github_api_url = 'https://api.github.com'

        # Extracting important details for pull request
        code_fix_dict = json.loads(code_fix)
        logger.info(f"Retrieved code fix")

        description = code_fix_dict.get('description')
        detailed_description = code_fix_dict.get('detailed_description')
        title = code_fix_dict.get('title')
        commit_message = code_fix_dict.get('commit_message')
        source_code = code_fix_dict.get('source_code')
        source_code_filename = source_code[0].get('filename')
        source_code_contents = source_code[0].get('contents')

        logger.info(f'Retrieved code fix details \n{description} \n{detailed_description} \n{title} \n{commit_message} \n{source_code_filename}')

        # Extract details for PR and file update
        pr_description = f'{description} \n\n {detailed_description}'
        pr_title = title

        # fix the file we fetched
        if not source_code_contents:
            raise ValueError("AI response did not contain modified code content.")

        # Update File with a fix
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json'
        }

        # d) Fetch Source Code from Base Branch
        content_url = f"{github_api_url}/repos/{repo_owner}/{repo_name}/contents/{file_path}?ref={github_dev_branch}"
        logger.info(f"Fetching content: {content_url}")
        # file_data = github_api_request('GET', content_url, headers, expected_status=200)
        file_data = requests.get(content_url, headers=headers)
        file_data.raise_for_status() # Raise an exception for HTTP errors
        file_data = file_data.json()
        file_content_base64 = file_data.get('content', '')
        file_sha = file_data.get('sha') # SHA needed for update
        if not file_content_base64 or not file_sha:
            raise ValueError(f"Could not retrieve content or SHA for {file_path} from branch {github_dev_branch}")

        code_update_url = f"{github_api_url}/repos/{repo_owner}/{repo_name}/contents/{file_path}"
        encoded_source_code_contents = base64.b64encode(source_code_contents.encode('utf-8')).decode('utf-8')
        update_payload = {
            'message': commit_message, # Use PR title as commit message
            'content': encoded_source_code_contents,
            'sha': file_sha, # Provide the original SHA
            'branch': github_dev_branch
        }            
        logger.info(f"Updating file {file_path} in branch {github_dev_branch}")

        code_update_response = requests.put(code_update_url, headers=headers, json=update_payload)
        logger.info(f'Code update Response : {code_update_response}')   
        code_update_response.raise_for_status() 

        # Create Pull Request
        pr_url_api = f"{github_api_url}/repos/{repo_owner}/{repo_name}/pulls"
        pr_payload = {
            'title': pr_title,
            'body': f"\n\n_Auto-generated by AI Self-Healing Lambda-AI Agent based on error log. \n{pr_description }",
            'head': github_dev_branch,
            'base': github_test_branch
        }

        logger.info(f"Creating Pull Request from {github_dev_branch} to {github_test_branch}")
        pr_response = requests.post(pr_url_api, headers=headers, json=pr_payload)
        logger.info(f'Pull Request Response : {pr_response}')   
        pr_response.raise_for_status() 
        pr_url = pr_response.get('html_url')
        logger.info(f"Successfully created Pull Request: {pr_url}")        

    except Exception as e:
        return {
            'statusCode': 500,
            'body': json.dumps({'error': 'Error occored while creating Pull Request. Check logs.'})
         }
    return {
        'statusCode': 200,
        # 'body': json.dumps({'': })
    }         