import json
import os
import requests
import logging
import time
import base64

# Configure logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def raise_PR(code_fix, file_path):
    try:
        # Extract environment variables
        logger.info("Extracting environment variables...")
        github_token = os.environ['GITHUB_TOKEN']
        repo_owner = os.environ['GITHUB_REPO_OWNER']
        repo_name = os.environ['GITHUB_REPO_NAME']
        github_dev_branch = 'feature/backend'
        github_test_branch = 'feature/test'
        github_api_url = 'https://api.github.com'

        # Extract details from code fix
        logger.info("Parsing code fix...")
        code_fix_dict = code_fix

        description = code_fix_dict.get('description', '')
        detailed_description = code_fix_dict.get('detailed_description', '')
        title = code_fix_dict.get('title', '')
        commit_message = code_fix_dict.get('commit_message', '')
        source_code = code_fix_dict.get('source_code', [])
        
        if not source_code:
            raise ValueError("No source code found in AI response.")

        source_code_filename = source_code[0].get('filename', '')
        source_code_contents = source_code[0].get('contents', '')

        logger.info(f"Parsed PR details: Title: {title}, File: {source_code_filename}, Description: {description}")

        if not source_code_contents:
            raise ValueError("AI response did not contain modified code content.")

        # Set up GitHub headers
        headers = {
            'Authorization': f'token {github_token}',
            'Accept': 'application/vnd.github.v3+json'
        }

        # Fetch current file data from base branch
        content_url = f"{github_api_url}/repos/{repo_owner}/{repo_name}/contents/{file_path}?ref={github_dev_branch}"
        logger.info(f"Fetching file content from {github_dev_branch}: {content_url}")

        file_data = requests.get(content_url, headers=headers)
        file_data.raise_for_status()
        file_data = file_data.json()

        file_content_base64 = file_data.get('content')
        file_sha = file_data.get('sha')

        if not file_content_base64 or not file_sha:
            raise ValueError(f"Could not retrieve content or SHA for file '{file_path}' from branch '{github_dev_branch}'")

        # Prepare file update
        encoded_source_code_contents = base64.b64encode(source_code_contents.encode('utf-8')).decode('utf-8')
        update_payload = {
            'message': commit_message,
            'content': encoded_source_code_contents,
            'sha': file_sha,
            'branch': github_dev_branch
        }

        code_update_url = f"{github_api_url}/repos/{repo_owner}/{repo_name}/contents/{file_path}"
        logger.info(f"Updating file '{file_path}' on branch '{github_test_branch}'")

        code_update_response = requests.put(code_update_url, headers=headers, json=update_payload)
        code_update_response.raise_for_status()
        logger.info("File updated successfully.")

        # Create pull request
        pr_url_api = f"{github_api_url}/repos/{repo_owner}/{repo_name}/pulls"
        pr_payload = {
            'title': title,
            'body': f"\n\n_Auto-generated by AI Self-Healing Lambda-AI Agent based on error log._\n\n{description}\n\n{detailed_description}",
            'head': github_dev_branch,
            'base': github_test_branch
        }

        logger.info(f"Creating pull request from '{github_dev_branch}' to '{github_test_branch}'...")
        pr_response = requests.post(pr_url_api, headers=headers, json=pr_payload)
        pr_response.raise_for_status()

        pr_json = pr_response.json()
        pr_url = pr_json.get('html_url', 'No URL returned')
        logger.info(f"Pull Request successfully created: {pr_url}")

        return {
            'statusCode': 200,
            'body': json.dumps({'pull_request_url': pr_url})
        }

    except requests.HTTPError as http_err:
        logger.error(f"HTTP error occurred: {http_err}", exc_info=True)
    except ValueError as val_err:
        logger.error(f"Value error: {val_err}", exc_info=True)
    except KeyError as key_err:
        logger.error(f"Missing environment variable or key: {key_err}", exc_info=True)
    except Exception as e:
        logger.error(f"Unexpected error: {e}", exc_info=True)

    return {
        'statusCode': 500,
        'body': json.dumps({'error': 'An error occurred while creating the Pull Request. Check logs for details.'})
    }