#version: 0.2
#
#phases:
#  install:
#    commands:
#      - echo Installing Maven...
#      - mvn --version
#  build:
#    commands:
#      - echo Building the Spring Boot app...
#      - mvn -f savannah-canopy-rest/pom.xml clean package
#      - ls savannah-canopy-rest/target
#      - pwd
#artifacts:
#  files:
#    - savannah-canopy-rest/target/*.jar


version: 0.2

#setting up environmental variables
env:
  variables:
    AWS_ACCOUNT_ID: "539247457480"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn -f savannah-canopy-rest/pom.xml clean package
      - echo Building the Docker image...
#      - docker build -f savannah-canopy-rest/Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:latest .
      - docker build --load -f savannah-canopy-rest/Dockerfile -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:latest . #looks for docker file
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/plantstore-backend-registry:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - savannah-canopy-rest/target/*.jar
    - imagedefinitions-backend.json #provide information to CodePipeline (or other deployment tools) about where to fetch the image from ECR