version: 0.2

phases:
  install:
    commands:
      - echo Installing Node...
      - cd savannah-canopy-web
      - node --version
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
artifacts:
  base-directory: savannah-canopy-web/build
  files:
    - '**/*'