spring.application.name=savannah-canopy

# Database configuration for PostgreSQL
# For production
spring.datasource.url=jdbc:postgresql://tf-20250326031031208500000001.cngeamecwr2q.us-east-1.rds.amazonaws.com:5432/postgres
aws.secretsmanager.secret-name=db_credentials

# For local development
#spring.datasource.url=jdbc:postgresql://localhost:5432/savannah_canopy_store_PG_DB
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# actuator health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never