spring.application.name=savannah-canopy

# Database configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/savannah_canopy_store_PG_DB
spring.datasource.username=postgres
spring.datasource.password=g00dp@$$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update  # Set to 'none' in production
#spring.jpa.show-sql=true  # Shows SQL queries in logs (for debugging)