spring.application.name=savannah-canopy

# actuator health check
management.endpoints.web.exposure.include=health,httptrace
management.endpoint.health.show-details=always

# AWS SDK logging
logging.level.software.amazon.awssdk=DEBUG