version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the Spring Boot app...
      - cd savannah-canopy-rest
      - mvn clean package
      - ls
      - pwd
artifacts:
  files:
    - savannah-canopy-rest/target/*.jar