version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo listing files...
      - ls
      - pwd
      - echo Building the Spring Boot app...
      - mvn clean package
      - echo listing files...
      - ls
      - pwd
artifacts:
  files:
    - target/*.jar